# Generated by Django 3.1.1 on 2020-09-29 14:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('volunteers', '0002_auto_20200929_1235'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=200, unique=True)),
                ('institution_name', models.CharField(max_length=150)),
                ('country', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('zipcode', models.CharField(max_length=15)),
                ('institution_type', models.CharField(choices=[('Environment', 'Environment'), ('Humanitarian', 'Humanitarian')], default='Humanitarian', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('verified', models.BooleanField(default=False)),
                ('photo_main', models.ImageField(upload_to='photos/%d/%m/%y/')),
                ('photo_1', models.ImageField(blank=True, upload_to='photos/%d/%m/%y/')),
                ('photo_2', models.ImageField(blank=True, upload_to='photos/%d/%m/%y/')),
                ('photo_3', models.ImageField(blank=True, upload_to='photos/%d/%m/%y/')),
                ('photo_4', models.ImageField(blank=True, upload_to='photos/%d/%m/%y/')),
                ('photo_5', models.ImageField(blank=True, upload_to='photos/%d/%m/%y/')),
                ('photo_6', models.ImageField(blank=True, upload_to='photos/%d/%m/%y/')),
                ('photo_7', models.ImageField(blank=True, upload_to='photos/%d/%m/%y/')),
                ('photo_8', models.ImageField(blank=True, upload_to='photos/%d/%m/%y/')),
                ('photo_9', models.ImageField(blank=True, upload_to='photos/%d/%m/%y/')),
                ('photo_10', models.ImageField(blank=True, upload_to='photos/%d/%m/%y/')),
                ('photo_11', models.ImageField(blank=True, upload_to='photos/%d/%m/%y/')),
                ('photo_12', models.ImageField(blank=True, upload_to='photos/%d/%m/%y/')),
                ('photo_13', models.ImageField(blank=True, upload_to='photos/%d/%m/%y/')),
                ('photo_14', models.ImageField(blank=True, upload_to='photos/%d/%m/%y/')),
                ('photo_15', models.ImageField(blank=True, upload_to='photos/%d/%m/%y/')),
                ('photo_16', models.ImageField(blank=True, upload_to='photos/%d/%m/%y/')),
                ('photo_17', models.ImageField(blank=True, upload_to='photos/%d/%m/%y/')),
                ('photo_18', models.ImageField(blank=True, upload_to='photos/%d/%m/%y/')),
                ('photo_19', models.ImageField(blank=True, upload_to='photos/%d/%m/%y/')),
                ('photo_20', models.ImageField(blank=True, upload_to='photos/%d/%m/%y/')),
                ('is_published', models.BooleanField(default=True)),
                ('list_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='volunteers.volunteer')),
            ],
        ),
    ]
